version: '3.7'

services:
  backend:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/tata
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
  database:
    image: library/postgres:13.0-alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tata
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d