server:
  servlet:
    context-path: /api

token:
  jwt:
    secret: secret
    expire: 3600000
  refresh:
    secret: secret
    expire: 36000000

spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/tata
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer-topic: topic-camera
    producer-group: group1
    consumer-topic: detect-trash

springdoc:
  api-docs:
    path: /openapi/docs
  swagger-ui:
    path: /openapi/swagger

cors:
  url: http://localhost:3000